# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: no-commit-to-branch
    -   id: check-executables-have-shebangs
    -   id: check-toml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: ^templates/
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: pretty-format-json
        args:
        - --autofix
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
    -   id: rst-linter
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        exclude: ".*lock.*"
        # args: ['--baseline', '.secrets.baseline']
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.97.0" # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
    -   id: terraform_fmt
    -   id: terraform_docs
    -   id: terraform_tflint
