on:
  schedule:
    - cron:  '30 5,17 * * *'
  pull_request:

jobs:
  sanitychecks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install dependencies
      id: install_dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit==3.4.0
    - name: pre-commit
      id: pre_commit
      run: |
        export SKIP=no-commit-to-branch
        pre-commit run --all-files
